version: 20.15.1
services:
  - type: web
    name: wanderway-web
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: no
    
   
